trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Install Microsoft SQL tools (sqlcmd)
- script: |
    set -e
    sudo apt-get update
    sudo ACCEPT_EULA=Y apt-get install -y curl apt-transport-https gnupg
    curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
    sudo apt-get update
    sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev
    echo "✅ mssql-tools18 installed successfully"
  displayName: 'Install sqlcmd (mssql-tools18)'

# Step 2: Apply your schema.sql file to the Azure SQL Database
- script: |
    set -euo pipefail
    set +H
    /opt/mssql-tools18/bin/sqlcmd \
      -S "tcp:dmprojserver.database.windows.net,1433" \
      -d "DMprojDB" \
      -U "alefia" \
      -P "#A032603aa" \
      -i "schema.sql"
  displayName: 'Apply schema.sql to DMprojDB'
