trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install sqlcmd (new, working version)
- script: |
    sudo apt-get update
    sudo ACCEPT_EULA=Y apt-get install -y curl apt-transport-https gnupg
    curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
    sudo apt-get update
    sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev
    echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
    source ~/.bashrc
    sqlcmd -? >/dev/null 2>&1 && echo "✅ sqlcmd installed successfully"
  displayName: 'Install sqlcmd (stable version)'

# Apply schema.sql to your Azure SQL Database
- script: |
    sqlcmd -S tcp:dmprojserver.database.windows.net,1433 \
           -d DMprojDB \
           -U alefia \
           -P $(SQL_PASSWORD) \
           -i schema.sql
  displayName: 'Apply schema.sql to DMprojDB'
