trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install sqlcmd
- task: Bash@3
  displayName: 'Install sqlcmd'
  inputs:
    targetType: inline
    script: |
      sudo apt-get update
      sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
      echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
      source ~/.bashrc
      sqlcmd -? >/dev/null 2>&1 && echo "sqlcmd installed"

# Apply schema to Azure SQL
- script: |
    sqlcmd -S tcp:dmprojserver.database.windows.net,1433 \
           -d DMprojDB \
           -U alefia \
           -P $(SQL_PASSWORD) \
           -i schema.sql
  displayName: 'Apply schema.sql to DMprojDB'
